RU = {1: 'Попытка авторизации...',
      2: 'Успешная авторизация. Код ответа: {}',
      3: 'Ошибка авторизации. Код ответа: {} ({})',
      4: 'Попытка получения информации о кластере...',
      5: 'Информация о кластере получена. Код ответа: {}',
      6: 'Не удалось получить информацию о кластере. Код ответа: {} ({})',
      7: 'Слишком высокая загрузка процессоров кластера',
      8: 'Миграция невозможна. Срочно примите мары!',
      9: '+++Загрузка памяти кластера не может быть больше 1, а тут {}!+++',
      10: '+++Загрузка CPU кластера не может быть больше 1, а тут {}!+++',
      11: 'Нет виртуальных машин/контейнеров или ошибка в методе Cluster.cluster_vms()',
      12: 'Запрос на миграцию {}',
      13: 'Миграция...',
      14: 'Ошибка при запросе миграции VM {} с {} на {}. Проверьте запрос.',
      15: '{} - Завершена!',
      16: 'Что-то пошло не так во время миграции. Код ответа {}',
      17: 'Загрузка ОЗУ кластера должна быть в диапазоне от 0 до 1 / ',
      18: 'Загрузка кластера {} %. Невозможно автоматически освободить хост.',
      19: ['№', 'Сервер', 'ОЗУ (GB)', 'Загружено (GB)', 'Загрузка в %', 'Кол-во VM', 'Список VM'],
      20: 'Нет запущенных VM',
      21: 'Список VM',
      22: 'Введите № хоста, который нужно освободить: ',
      23: 'Выбран {}',
      24: 'Неверный ввод. Повторите попытку',
      25: 'Недостаточно свободного ОЗУ кластера чтобы освободить {}',
      26: 'Недостаточно свободных процессоров кластера чтобы освободить {}',
      27: 'Данный хост содержит контейнеры. Нужно иметь ввиду что контейнеры при миграции перезагружаются',
      28: 'Список контейнеров: {}',
      29: 'Напишите "YES" для продолжения: ',
      30: 'Перенесите контейнеры вручную и перезапустите скрипт',
      31: 'Проверяем наличие локальных ресурсов у виртуальных машин...',
      32: 'Эти VM {} имеют локальные ресурсы. Это могут быть CD-ROM или локальные диски,',
      33: 'размещенные на хосте. В первом случае нужно отключить диск, во втором - перенести машину',
      34: 'вручную указав новое расположение для дисков. Затем перезапустите скрипт.',
      35: 'Производим проверочные вычисления для VM {} и реципиента {}',
      36: 'Виртуальная машина {} не помещается на максимально свободный хост {}',
      37: 'Всё готово для начала миграции VM!',
      38: 'Начинаем через {}...',
      39: 'Мигрируем VM {} на {}',
      40: 'Миграция {} не завершена, проверьте состояние хоста.',
      41: '{} освобождён!'}

EN = {1: 'Authorization attempt...',
      2: 'Successful authorization. Response code: {}',
      3: 'Authorization error. Response code: {} ({})',
      4: 'An attempt to obtain information about the cluster...',
      5: 'Information about the cluster has been received. Response code: {}',
      6: 'Failed to get cluster information. Response code: {} ({})',
      7: 'Cluster CPU usage is too high',
      8: 'Migration is not possible. Urgently accept Mary!',
      9: '+++The cluster memory load cannot be more than 1, and here {}!+++',
      10: '+++The CPU load of the cluster cannot be more than 1, and here {}!+++',
      11: 'No VMs/containers or error in the Cluster.cluster_vms() method',
      12: 'Migration request {}',
      13: 'Migration...',
      14: 'Error when requesting VM {} migration from {} to {}. Check the request.',
      15: '{} - Completed!',
      16: 'Something went wrong during the migration. Response code {}',
      17: 'Cluster RAM load should be in the range from 0 to 1 / ',
      18: 'Cluster load {} %. It is not possible to release the host automatically.',
      19: ['№', ' Server', 'RAM (GB)', 'Uploaded (GB)', 'Loading in %', 'Number of VMs', 'List of VMs'],
      20: 'No running VMs',
      21: 'List of VMs',
      22: 'Enter the host number to be released: ',
      23: 'Selected {}',
      24: 'Invalid input. Try again',
      25: 'Not enough free cluster RAM to free {}',
      26: 'There are not enough free cluster processors to free {}',
      27: 'This host contains containers. It should be borne in mind that containers are reloaded during migration',
      28: 'List of containers: {}',
      29: 'Write "YES" to continue: ',
      30: 'Move the containers manually and restart the script',
      31: 'Checking the availability of local resources for virtual machines...',
      32: 'These VMs {} have local resources. These can be CD-ROMs or local disks,',
      33: 'hosted on the host. In the first case, you need to disconnect the disk, in the second - move the machine',
      34: 'manually specifying a new location for the disks. Then restart the script.',
      35: 'Performing verification calculations for VM {} and recipient {}',
      36: 'The virtual machine {} does not fit on the maximum free host {}',
      37: 'Everything is ready to start VM migration!',
      38: 'Starting in {}...',
      39: 'Migrating VM {} to {}',
      40: 'Migration {} is not completed, check the status of the host.',
      41: '{} released!'}

GR = {1: 'Versuch der Autorisierung...',
      2: 'Erfolgreiche Autorisierung. Antwortcode: {}',
      3: 'Autorisierungsfehler. Antwortcode: {} ({})',
      4: 'Es wurde versucht, Informationen über den Cluster zu erhalten...',
      5: 'Clusterinformationen erhalten. Antwortcode: {}',
      6: 'Die Clusterinformationen konnten nicht abgerufen werden. Antwortcode: {} ({})',
      7: 'Cluster-CPU-Auslastung zu hoch',
      8: 'Migration ist nicht möglich. Nehmt Mara sofort!',
      9: '+++Die Auslastung des Clusterspeichers darf nicht größer als 1 sein, und hier {}!+++',
      10: '+++Die CPU-Auslastung des Clusters darf nicht größer als 1 sein, und hier {}!+++',
      11: 'Keine virtuellen Maschinen/Container oder Fehler in der Cluster-Methode.cluster_vms()',
      12: 'Migrationsanforderung {}',
      13: 'Migration...',
      14: 'Fehler beim Anfordern der VM {}-Migration von {} zu {}. Überprüfen Sie die Anfrage.',
      15: '{} - Fertig!',
      16: 'Etwas ist während der Migration schief gelaufen. Antwortcode {}',
      17: 'Die RAM-Auslastung des Clusters muss zwischen 0 und 1 / liegen ',
      18: 'Cluster-Auslastung {} %. Der Host kann nicht automatisch freigegeben werden.',
      19: ['#', 'Server', 'RAM (GB)', 'Geladen (GB)', 'Laden in %', 'Anzahl der VM', 'Liste der VM'],
      20: 'Keine laufenden VMs',
      21: 'Liste der VM',
      22: 'Geben Sie die Nummer des zu löschenden Hosts ein: ',
      23: '{}ausgewählt',
      24: 'Falsche Eingabe. Versuchen Sie es erneut',
      25: 'Nicht genügend freier Arbeitsspeicher für den Cluster, um {} freizugeben',
      26: 'Nicht genügend freie Cluster-Prozessoren, um {} freizugeben',
      27: 'Dieser Host enthält Container. Beachten Sie, dass die Container bei der Migration neu geladen werden',
      28: 'Liste der Container: {}',
      29: 'Schreibe "YES", um fortzufahren: ',
      30: 'Container manuell migrieren und das Skript neu starten',
      31: 'Überprüfen Sie, ob lokale Ressourcen in den virtuellen Maschinen vorhanden sind...',
      32: 'Diese VMs {} haben lokale Ressourcen. Dies können CD-Roms oder lokale Laufwerke sein,',
      33: 'auf dem Host gehostet. Im ersten Fall müssen Sie die Festplatte deaktivieren, im zweiten Fall die Maschine verschieben',
      34: 'manuell einen neuen Speicherort für die Laufwerke angeben. Starten Sie dann das Skript neu.',
      35: 'Validierungsberechnungen für VM {} und Empfänger {}',
      36: 'Die virtuelle Maschine {} passt nicht auf den maximal freien Host {}',
      37: 'Sie sind bereit, die VM-Migration zu starten!',
      38: 'Wir beginnen durch {}...',
      39: 'VM {} nach {} migrieren',
      40: 'Die Migration {} ist nicht abgeschlossen, überprüfen Sie den Hoststatus.',
      41: '{} befreit!'}

if __name__ == "__main__":
      pass
